services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=brq#12345
      - MSSQL_TCP_PORT=1433
    expose:
      - "1433"
    ports:
      - "1433:1433"